import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Apus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className='font-bold underline text-orange-400'>Empresa ainda sem nome</h1>
      </main>
    </>
  )
}
